# Generated by Django 2.0.6 on 2020-05-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(),
        ),
    ]
